---
# tasks file for prod
- name: Ensure tomcat package is present
  apt:
    name: tomcat9
    state: present

- name: Ensure tomcat service is started
  service:
    name: tomcat9
    state: started

- name: Transfer file from build to prod
  synchronize:
    src: "{{ src_folder }}"
    dest: "{{ dest_folder }}"
  delegate_to: "{{build_ip_address}}"
