FROM ubuntu:20.04
WORKDIR /var/boxfuse/
VOLUME /var/boxfuse/
RUN apt update
RUN apt -y install maven default-jdk
RUN apt -y install git
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /var/boxfuse
RUN mvn package
RUN cp target/hello-1.0.war /var/boxfuse/