---
version: '3'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8383:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: authservice
    volumes:
      - /var/lib/mysql:/var/lib/mysql


