---
- name: Install java
  hosts: build
  become: yes

  tasks:
  - name: Ensure java package is present
    apt:
      update_cache: yes
      name: default-jdk
      state: present

  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Ensure git package is present
    apt:
      name: git
      state: present

  - name: Ensure git repository clone is present
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /boxfuse
      clone: yes
      force: yes

  - name: Ensure new pom.xml is present
    copy:
      src: pom.xml
      dest: /boxfuse/

  - name: Ensure artifact is present
    command: mvn package -f /boxfuse/pom.xml

- name: Install tomcat
  hosts: prod
  become: yes


  tasks:
  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure tomcat service is started
    service:
      name: tomcat9
      state: started


  - name: Transfer file from build to prod
    synchronize:
      src: /boxfuse/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/
    delegate_to: 84.201.167.225

